name: test

on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Nargo
      uses: noir-lang/noirup@v0.10.5
      with:
        toolchain: nightly

    - name: Run tests
      run: |
        nargo test